### ISSUE TITLE
Sign Up always shows User with same name already exists rather there is another problem

### ISSUE THREAD

**Issue by Bhawna11agg** [AOSSIE-Org/Agora-Android#2]
During Sign up if I left an edit text blank then also in Toast it is showing User with the same name already exists with the error,it must not happen as it makes users confuse and there is no compulsion for a user to not put white space in the starting of First Name, User name, etc.

**Comment by ankushmundhra** [comment]
i will work on this.

**Comment by Bhawna11agg** [comment]
May I work on this?

**Comment by ankushmundhra** [comment]
@Bhawna11agg i am working on this

**Comment by Bhawna11agg** [comment]
Ok

**Comment by ankushmundhra** [comment]
@Bhawna11agg please check PR request.
